# Generated by Django 4.2.7 on 2024-12-05 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CJ', 'Candies Jars'), ('PC', 'Potato Chips'), ('CA', 'Cake'), ('BI', 'Biscuit'), ('JU', 'Juice'), ('CH', 'Chocolate')], default='CA', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='snack',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Canteen.category'),
        ),
    ]
